export 'home/home.dart';
export 'wishlist/wishlist.dart';
export 'blog/blog.dart';
export 'account/account.dart';
export 'category/category.dart';
export 'property_list/property_list.dart';
export 'property_detail/property_detail.dart';
export 'property_gallery/property_gallery.dart';
export 'properties/properties.dart';
